nguage: c
dist: trusty
sudo: required
addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - linux-headers-$(uname -r)
    - gcc
    - linux-libc-dev
    - libpopt-dev
    - libssl-dev
    - libnuma-dev
    - curl
    - sshpass
compiler:
- gcc
install:
- curl www.qq.com
jobs:
  include:
  - stage: dpdkbuild
    script:
    - ssh root@115.182.224.11 -o stricthostkeychecking=no ' pwd '
before_install:
- openssl aes-256-cbc -K $encrypted_784862453097_key -iv $encrypted_784862453097_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 115.182.224.11\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
