nguage: c
dist: trusty
sudo: required
addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - linux-headers-$(uname -r)
    - gcc
    - linux-libc-dev
    - libpopt-dev
    - libssl-dev
    - libnuma-dev
    - curl
    - sshpass
compiler:
- gcc
install:
       - curl www.qq.com

jobs:
   include :
    - stage:  dpdkbuild
      script:
        - ssh root@47.95.5.155 -o stricthostkeychecking=no ' rm -rf dpvs/ && git clone https://github.com/cxd0513/dpvs.git && cd dpvs && chmod +x dpdkbuild.sh && . .dpdkbuild.sh '


before_install:

- openssl aes-256-cbc -K $encrypted_91258f690662_key -iv $encrypted_91258f690662_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 47.95.5.155\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

